"use client";

import { cn } from "@/lib/utils";
import "./globals.css";
import Socials from "@/components/Socials";
import { useState, useEffect } from "react";
import Loader from "@/components/Loader";

// export const metadata = {
//   title: "Trey Rader - Portfolio 2024",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isLoading, setIsLoading] = useState(
    process.env.NODE_ENV === "development" ? false : true
  );

  // const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const LocomotiveScroll = (await import("locomotive-scroll")).default;
      const locomotiveScroll = new LocomotiveScroll();

      setTimeout(() => {
        setIsLoading(false);
        document.body.style.cursor = "default";
        window.scrollTo(0, 0);
      }, 1700);
    })();
  }, []);

  return (
    <html lang="en">
      <body
        className={cn(
          { loading: isLoading },
          "bg-foreground",
          // "cursor-none",
          "scroll-smooth",
          // "pointer-events-none",
          "max-w-screen",
          "delay-[2s]"
        )}
      >
        {isLoading ? <Loader /> : children}
        <Socials />
      </body>
    </html>
  );
}
